---
- name: Uninstall Jenkins
  hosts: jenkins
  gather_facts: true
  become: yes
  become_method: sudo
  tags: [remove]

  tasks:
  - name: Stop jenkins Server
    service:
      name: jenkins
      state: stopped

  - name: Uninstall Package
    package:
      name: "{{ item }}"
      state: absent
    with_items:
      - jenkins
